### ISSUE TITLE
Unable to find a specification for `BedgeNotificHub`

### ISSUE THREAD

**Issue by wisisimon** [jogendra/BedgeNotificHub#1]
Hello~i got an error when pod install
please help me, thank you!

**Comment by muescha** [comment]
Can you copy the output from console?

**Comment by wisisimon** [comment]
<img width="888" alt="2019-02-17 12 01 54" src="https://user-images.githubusercontent.com/10337181/52908216-3cf58d80-32ac-11e9-9a92-a99ef78abaf0.png">
